name: üöÄ Deploy Frontend to Apache2 VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ----------------- CHECKOUT -----------------
      - name: üß© Checkout c√≥digo
        uses: actions/checkout@v4

      # ----------------- NODE -----------------
      - name: ‚öô Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # ----------------- DEPENDENCIAS -----------------
      - name: üí° Instalar Angular CLI
        run: npm install -g @angular/cli

      - name: üì¶ Instalar dependencias frontend
        run: npm install

      # ----------------- BUILD FRONTEND -----------------
      - name: üèó Build frontend
        run: ng build --configuration production --base-href /

      # ----------------- PREPARAR FRONTEND -----------------
      - name: üß© Preparar archivos frontend
        run: |
          rm -rf deploy-frontend
          mkdir deploy-frontend
          # copiar solo el contenido de la build, no la carpeta entera
          cp -r dist/front-end/browser/* deploy-frontend/
          cp dist/front-end/3rdpartylicenses.txt deploy-frontend/ || true
          cp dist/front-end/prerendered-routes.json deploy-frontend/ || true

      # ----------------- DEBUG -----------------
      - name: üßæ Ver contenido listo para deploy
        run: ls -R deploy-frontend

      # ----------------- LIMPIAR CARPETA DEL FRONTEND -----------------
      - name: üßπ Limpiar solo deploy-frontend en el servidor
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          script: |
            rm -rf /var/www/jose_site/deploy-frontend/*
            mkdir -p /var/www/jose_site/deploy-frontend
            echo "‚úî Solo deploy-frontend fue limpiado"

      # ----------------- SUBIR ARCHIVOS -----------------
      - name: üì§ Subir frontend al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          source: "deploy-frontend/*"   
          target: "/var/www/jose_site/deploy-frontend/"  
          overwrite: true

      # ----------------- SSH TASKS -----------------
      - name: ‚öô Configurar permisos finales
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          script: |
            echo "‚úî Deploy completado"
